; PlatformIO project for ESP32 SWIM programmer
; Currently: ESP32 acts as a simple NRST pulse generator
; The STM8 is programmed via stm8gal talking to the CH340 on the dongle

[env:esp32dev]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
upload_speed    = 921600

build_flags     =
    -DCORE_DEBUG_LEVEL=3

lib_deps        =
